In [3]:
# Test to see if Numpy is installed
import numpy as np

# Introduction to numpy:

Numpy (Numerical Python), is a module on which that most  
common data science packages are built. It allows us to  
work with multi-dimensional arrays really quickly  
which we can use as vectors or matrices.

# `ndarray`

**ndarrays** are time and space-efficient multidimensional  
arrays at the core of numpy. 

## Creating Rank 1 numpy arrays:

In [8]:
import numpy as np

foo = np.array([3, 33, 333])     # rank 1 array

print(type(foo))

<class 'numpy.ndarray'>


In [9]:
# tests the shape of the array, i.e. how many dimensions
print(foo.shape)

(3,)


In [10]:
print(foo[0], foo[1], foo[2])

3 33 333


In [12]:
foo[0] = 888

print(foo)

[888  33 333]


## Creating Rank 2 numpy arrays:

A rank 2 **ndarray** is one with two dimensions. 2-dimensional arrays  
are great for representing matrices which are often used in  
data sciences.

In [21]:
bar = np.array([[11, 12, 13], [21, 22, 23]])   # rank 2 array

print(bar)
print("The shape is 2 rows, 3 columns", bar.shape)     # rows and columns
print("Accessing elements [0, 0], etc...")
print(bar[0, 0])
print(bar[0, 1])
print(bar[1][0])   # This also works

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns (2, 3)
Accessing elements [0, 0], etc...
11
12
21


## Creating Arbitrary Arrays

We can create a number of different size arrays  
with different shapes and different pre-filled  
values. numpy has a number of built-in functions  
to help use create these.

In [22]:
import numpy as np

# create a 2x2 array of zeros
zero_array = np.zeros((2, 2))
print(zero_array)

[[0. 0.]
 [0. 0.]]


In [25]:
# create a 2x2 array filled with 8.0
eight_array = np.full((2, 2), 8.0)
print(eight_array)

[[8. 8.]
 [8. 8.]]


In [27]:
# create a 2x2 array with diagonal 1s and 0s
diag_array = np.eye(10, 10)
print(diag_array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [30]:
# create an array of ones
ones_array = np.ones((1, 2))
print(ones_array)

[[1. 1.]]


# shape of the above array is actually rank 2
print(ones_array.shape)
# because it's rank 2, we need 2 values to access elements
print(ones_array[0, 1])

In [34]:
# create an array of random floats between 0 and 1
random_array = np.random.random((2,2))
print(random_array)

[[0.92909066 0.18210007]
 [0.99720954 0.88702566]]


# Slicing and Array Indexing

## Slice indexing:

Similar to the use of slice indexing with strings and lists.  
We can use the same method with `ndarrays`.

In [1]:
import numpy as np

# Rank 2 of shape (3, 4) -- (rows, cols)
foo = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34]
])

print(foo)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [10]:
# Use array slicing to get a subarray of [12, 13], [22, 23]
slice_of_foo = foo[:2, 1:3]
print(slice_of_foo)

[[12 13]
 [22 23]]


In [13]:
# When you modify a slice, you actually modify
# the ORIGINAL ARRAY
print(foo)
slice_of_foo[0, 0] = 1000
print(foo)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


We can use both integer and slice indexing.

We can use them in combination to create differently  
shaped arrays.

In [14]:
# Create a rank 2 array of shape (3, 4)
bar = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(bar)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [19]:
# Use both integer and slice indexing to create a lower-ranked array
row_1_bar = bar[1, :]
print(row_1_bar, row_1_bar.shape)

[21 22 23 24] (4,)


In [20]:
# Slice the middle row so it gets just 22, 23
row_1_bar_slice = bar[1, 1:3]
print(row_1_bar_slice, row_1_bar_slice.shape)

[22 23] (2,)


In [22]:
# We can also do the same thing with columns
col_1_bar = bar[:, 1]
print(col_1_bar, col_1_bar.shape)

col_1_bar_samerank = bar[:, 1:2]
print(col_1_bar_samerank, col_1_bar_samerank.shape)

[12 22 32] (3,)
[[12]
 [22]
 [32]] (3, 1)


### Array Indexing

Sometimes it's useful to use an array of indexes  
to access or to change elements.

In [23]:
import numpy as np

foobar = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])

print(foobar)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [27]:
# Create an array of indexes
col_indexes = [0, 1, 2]
row_indexes = [0, 1, 2]

for row, col in zip(row_indexes, col_indexes):
    print(row, col)
    
# list(zip(row_indexes, col_indexes))

0 0
1 1
2 2


In [28]:
# Select using the array of indexes
print("The values at those indexes are: ")
print(foobar[row_indexes, col_indexes])

The values at those indexes are: 
[11 22 33]


In [49]:
# Modify the values at those indexes
print(foobar)
foobar[row_indexes, col_indexes] += 1000
print(foobar)

[[20011    12    13    14]
 [   21 20022    23    24]
 [   31    32 20033    34]]
[[21011    12    13    14]
 [   21 21022    23    24]
 [   31    32 21033    34]]
