In [3]:
# Test to see if Numpy is installed
import numpy as np

# Introduction to numpy:

Numpy (Numerical Python), is a module on which that most  
common data science packages are built. It allows us to  
work with multi-dimensional arrays really quickly  
which we can use as vectors or matrices.

# `ndarray`

**ndarrays** are time and space-efficient multidimensional  
arrays at the core of numpy. 

## Creating Rank 1 numpy arrays:

In [8]:
import numpy as np

foo = np.array([3, 33, 333])     # rank 1 array

print(type(foo))

<class 'numpy.ndarray'>


In [9]:
# tests the shape of the array, i.e. how many dimensions
print(foo.shape)

(3,)


In [10]:
print(foo[0], foo[1], foo[2])

3 33 333


In [12]:
foo[0] = 888

print(foo)

[888  33 333]


## Creating Rank 2 numpy arrays:

A rank 2 **ndarray** is one with two dimensions. 2-dimensional arrays  
are great for representing matrices which are often used in  
data sciences.

In [21]:
bar = np.array([[11, 12, 13], [21, 22, 23]])   # rank 2 array

print(bar)
print("The shape is 2 rows, 3 columns", bar.shape)     # rows and columns
print("Accessing elements [0, 0], etc...")
print(bar[0, 0])
print(bar[0, 1])
print(bar[1][0])   # This also works

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns (2, 3)
Accessing elements [0, 0], etc...
11
12
21


## Creating Arbitrary Arrays

We can create a number of different size arrays  
with different shapes and different pre-filled  
values. numpy has a number of built-in functions  
to help use create these.

In [22]:
import numpy as np

# create a 2x2 array of zeros
zero_array = np.zeros((2, 2))
print(zero_array)

[[0. 0.]
 [0. 0.]]


In [25]:
# create a 2x2 array filled with 8.0
eight_array = np.full((2, 2), 8.0)
print(eight_array)

[[8. 8.]
 [8. 8.]]


In [27]:
# create a 2x2 array with diagonal 1s and 0s
diag_array = np.eye(10, 10)
print(diag_array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [30]:
# create an array of ones
ones_array = np.ones((1, 2))
print(ones_array)

[[1. 1.]]


In [33]:
# shape of the above array is actually rank 2
print(ones_array.shape)
# because it's rank 2, we need 2 values to access elements
print(ones_array[0, 1])

(1, 2)
1.0


In [34]:
# create an array of random floats between 0 and 1
random_array = np.random.random((2,2))
print(random_array)

[[0.92909066 0.18210007]
 [0.99720954 0.88702566]]
